# Generated by Django 5.0.3 on 2024-07-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA', models.DateField()),
                ('OPERACAO', models.CharField(max_length=255)),
                ('ATIVO', models.CharField(max_length=255)),
                ('Quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Preço', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CORRETORA', models.CharField(max_length=255)),
                ('NOTA', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
